/*Q3. Inheritance

Write a java application to maintain information for xyz sports club. The
sports club wants to store employee details, for each employee store
id, name, mobile no, emailid, Department, designation, Date of joining.
Employees are of 3 types salaried employee or contract employee,Vendors. If employee is
salaried employee, then store basic salary and if it is contract employee then store no of hrs
worked and per hour rate and if it is vendor then store no_of _employees, amount
Also store information about members of club
For each member store id, name, mobile no, emailid, type of membership, amount paid.
For employee and members, id is autogenerated
design a menu driven program to perform following

Calculate net salary by using following formula
1. Salaried Employee
Basic+DA+HRA-pf
DA-10% of basic
HRA – 15% of basic
Pf – 12% of Basic
2. Contract Employee
Hr rate * no of hrs worked
3 Vendor

amt+Amt*18% GST
Also store information about members of club
For each member store id, name, mobile no, emailid, type of membership, amount paid.
For employee and members, id is autogenerated
design a menu driven program to perform following
1. Display All employees (ask user salaried/contract employee display only one type of emplyees
based on selection)
2. Search by id
3. Search by name
4. Display all employee
5. calculate salary and display for all emplyees with particular designation
6. accept department from user and display 5 employees of that department.
5. Exit */

package com.hub;

public class Employee {
    static int counter = 1;

    int id;
    String name, mobile, email, dept, designation, doj;

    public Employee() {
        id = counter++; 
    }

    public void accept(java.util.Scanner sc) {
        System.out.print("Enter Name: ");
        name = sc.nextLine();

        System.out.print("Enter Mobile: ");
        mobile = sc.nextLine();

        System.out.print("Enter Email: ");
        email = sc.nextLine();

        System.out.print("Enter Department: ");
        dept = sc.nextLine();

        System.out.print("Enter Designation: ");
        designation = sc.nextLine();

        System.out.print("Enter Date of Joining: ");
        doj = sc.nextLine();
    }

    public void display() {
        System.out.println("\nID: " + id + " Name: " + name + " Dept: " + dept + " Designation: " + designation);
    }
}
